import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fast Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../asset/logoMoto.png" />
      </Head>
      <main className="">
        <div className="logo">
          <img src="../asset/logoMoto.png" alt="" />
        </div>
        <div className="login"></div>
      </main>
    </>
  );
}
