version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  back:
    image: "franciscoalvarezraineri/fd-backend:0.1.1"
    ports:
      - "8080:8080"
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: FastDelivery
    volumes:
      - ./mongo:/data/db
