name: Backend Deployment

on:
  push:
    branches: [master]

env:
  PROJECT_ID: fast-delivery-uma
  REGION: us-east1

jobs:
  build-and-deploy-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          project_id: fast-delivery-uma
          service_account: "github-actions@fast-delivery-uma.iam.gserviceaccount.com"
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: LogIn to Docker
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
      - name: Build Docker Image
        run: docker build -t us-east1-docker.pkg.dev/fast-delivery-uma/deploy/backend ./fd-backend/
      - name: Push Image to Artifact Registry
        run: docker push us-east1-docker.pkg.dev/fast-delivery-uma/deploy/backend
      - name: Deploy Image with Google Run
        run: gcloud run deploy backend --image us-east1-docker.pkg.dev/fast-delivery-uma/deploy/backend --region us-east1
